### ISSUE TITLE
repair build please

### ISSUE THREAD

**Issue by Zer0n4ik** [ocvcoin/ocv2_algo#1]
# Error libocv2.so in ubuntu:focal //tested
## ./minerd: error while loading shared libraries: libocv2.so: cannot open shared object file: No such file or directory

Can add symlink after cp (copy) lib in /usr/local/lib/libocv2.so

/// Command
ln -s /usr/local/lib/libocv2.so /lib/libocv2.so

Maybe i can help you? 
I can build pipeline for build minerd and libocv2.so or deb package with install in path lib and minerd.

Thanks

**Comment by ocvcoin** [comment]
thank you. fixed. 
autoinstall script for debian would be nice

**Comment by Zer0n4ik** [comment]
just maybe make not dynamic library, 

make static library libocv2.a and include he in cpuminer binary file?
